---

- stat: path=/usr/bin/atom
  register: atom_stat
  when: editors.atom

- name: Downloading atom
  get_url: url=https://atom.io/download/deb dest=/tmp/atom.deb
  when: editors.atom and not atom_stat.stat.exists

- name: Installing atom
  apt: deb=/tmp/atom.deb
  when: editors.atom and not atom_stat.stat.exists

- name: Getting users on system
  shell: "getent passwd | awk -F: '$3 >= 1000 && $3 <= 2000 { print $1 }'"
  register: system_users

- name: Installing visual-studio-code
  shell: /usr/bin/umake ide visual-studio-code /home/{{ item }}/.local/share/umake/ide/visual-studio-code --accept-license
  args:
    creates: /home/{{ item }}/.local/share/umake/ide/visual-studio-code
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ system_users.stdout_lines }}"
  when: editors.visual_studio_code

- name: Installing webstorm
  shell: /usr/bin/umake ide webstorm /home/{{ item }}/.local/share/umake/ide/webstorm
  args:
    creates: /home/{{ item }}/.local/share/umake/ide/webstorm
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ system_users.stdout_lines }}"
  when: editors.webstorm

- name: Installing phpstorm
  shell: /usr/bin/umake ide phpstorm /home/{{ item }}/.local/share/umake/ide/phpstorm
  args:
    creates: /home/{{ item }}/.local/share/umake/ide/phpstorm
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ system_users.stdout_lines }}"
  when: editors.phpstorm

- name: Installing pycharm
  shell: /usr/bin/umake ide pycharm /home/{{ item }}/.local/share/umake/ide/pycharm
  args:
    creates: /home/{{ item }}/.local/share/umake/ide/pycharm
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ system_users.stdout_lines }}"
  when: editors.pycharm

- name: Installing idea
  shell: /usr/bin/umake ide idea /home/{{ item }}/.local/share/umake/ide/idea
  args:
    creates: /home/{{ item }}/.local/share/umake/ide/idea
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ system_users.stdout_lines }}"
  when: editors.idea

- name: Installing idea-ultimate
  shell: /usr/bin/umake ide idea-ultimate /home/{{ item }}/.local/share/umake/ide/idea-ultimate
  args:
    creates: /home/{{ item }}/.local/share/umake/ide/idea-ultimate
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ system_users.stdout_lines }}"
  when: editors.idea_ultimate