---

- name: Add webupd8team sublime-text-3 PPA
  apt_repository: repo='ppa:webupd8team/sublime-text-3'

- name: Installing sublime-text
  package: name='sublime-text-installer'

- name: Getting users on system
  shell: "getent passwd | awk -F: '$3 >= 1000 && $3 <= 2000 { print $1 }'"
  register: system_users

- name: Installing visual-studio-code
  command: umake ide visual-studio-code /home/anthony/.local/share/umake/ide/visual-studio-code --accept-license
  args:
    creates: /home/anthony/.local/share/umake/ide/visual-studio-code
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ system_users.stdout_lines }}"

- name: Installing webstorm
  command: umake ide webstorm /home/anthony/.local/share/umake/ide/webstorm
  args:
    creates: /home/anthony/.local/share/umake/ide/webstorm
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ system_users.stdout_lines }}"

- name: Installing phpstorm
  command: umake ide phpstorm /home/anthony/.local/share/umake/ide/phpstorm
  args:
    creates: /home/anthony/.local/share/umake/ide/phpstorm
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ system_users.stdout_lines }}"

- name: Installing pycharm
  command: umake ide pycharm /home/anthony/.local/share/umake/ide/pycharm
  args:
    creates: /home/anthony/.local/share/umake/ide/pycharm
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ system_users.stdout_lines }}"
  
- name: Installing idea-ultimate
  command: umake ide idea-ultimate /home/anthony/.local/share/umake/ide/idea-ultimate
  args:
    creates: /home/anthony/.local/share/umake/ide/idea-ultimate
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ system_users.stdout_lines }}"