---

- name: Installing multimedia app (cli)
  apt:
    name: "{{item}}"
  with_items:
    - ffmpeg
    - mediainfo
    - libimage-exiftool-perl

- name: Installing multimedia apps (gui)
  apt:
    name: "{{item}}"
  when: gui
  with_items:
    - mediainfo-gui
    - gimp
    #- rawstudio
    - rawtherapee
    - kazam
    - vlc


# TODO: use snap for spotify
#- name: Adding spotify repository key
#  apt_key: keyserver=keyserver.ubuntu.com id=EFDC8610341D9410
#  when: gui
#
#- name: Adding spotify repository
#  apt_repository: repo='deb http://repository.spotify.com stable non-free' state=present
#  when: gui
#
#- name: Installing spotify
#  apt:
#    name: spotify-client
#  when: gui