---

- name: Installing multimedia app (cli)
  apt:
    name: "{{item}}"
  with_items:
    - ffmpeg
    - mediainfo
    - libimage-exiftool-perl

- name: Installing multimedia apps (gui)
  apt:
    name: "{{item}}"
  when: gui
  with_items:
    - mediainfo-gui
    - gimp
    #- rawstudio
    - rawtherapee
    - kazam
    - vlc
    - gpsbabel
    - hugin

- name: Installing spotify
  shell:
    snap install spotify
  creates: "/snap/bin/spotify"
  when: gui