---

- hosts: all
  become: yes
  become_user: root
  vars:
    gui: True
    nodejs_version: "4.x"
    nodejs_install_npm_user: "anthony"
    shorewall:
      externalPorts:
        - eno1
        - wlp2s0
      externalTCPAllowPorts:
          - 22
      externalUDPAllowPorts: []
      internalPorts:
        - lxdbr0
        - virbr0
        - tun0
        - docker0
      masquerade: True
      wait_interface: "eno0 wlp2s0"
    shorewall6:
      externalPorts:
        - eno1
        - wlp2s0
      externalTCPAllowPorts:
          - 22
      externalUDPAllowPorts: []
      internalPorts:
        - lxdbr0
        - virbr0
        - tun0
        - docker0
      masquerade: True
      wait_interface: "eno0 wlp2s0"

  pre_tasks:
    - set_fact: network_manager_unmanaged_devices={{[]}}

  roles:
    - clear-unused-apps
    - btrfs-tools
    - extra-filesystems
    - security-tools
    - tools
    - browsers
    - editors
    - multimedia
    - office
    - remote-control-apps
    - virtualization
    - ubuntu-customization
    - dev-tools
    - composer
    - nodejs
    - communication-apps
    - lxd
    - docker
    - shorewall
    - shorewall6
    - golang

  post_tasks:
    - ini_file: dest=/etc/NetworkManager/NetworkManager.conf
                section=keyfile
                option=unmanaged-devices
                value={{network_manager_unmanaged_devices|join(',')}}
                backup=yes

