---

- name: Installing minimal desktop
  apt:
    name: "{{item}}"
    install_recommends: False
  with_items:
    - ubuntu-gnome-desktop
    - plymouth-theme-ubuntu-logo
    - plymouth-theme-ubuntu-text
    - xfce4
    - xfce4-power-manager
    - gtk3-engines-xfce
    - thunar-archive-plugin
    - activity-log-manager-control-center
    - zeitgeist
    - network-manager-gnome
    - network-manager-vpnc
    - network-manager-vpnc-gnome
    - gedit
    - evince
    - eog
    - gnome-terminal
    - terminator
    - nano
    - dnsutils
    - traceroute
    - mtr-tiny
    - wireshark
    - gnome-disk-utility
    - testdisk
    # gnome-shell: system-monitor extension
    - gir1.2-gtop-2.0
    - gir1.2-networkmanager-1.0
