---

- name: Installing network tools
  apt:
    name: "{{item}}"
  with_items:
    - bridge-utils

- name: Installing LXD/LXC
  apt:
    name: "{{item}}"
  with_items:
    - lxd
    - lxd-client
    - lxcfs
    - dnsmasq # For custum config in /etc/dnsmasq.d/

- name: Getting users on system
  shell: "getent passwd | awk -F: '$3 >= 1000 && $3 <= 2000 { print $1 }'"
  register: system_users

- name: "Add lxd group to users"
  user: name={{item}} groups=lxd append=yes
  with_items: "{{ system_users.stdout_lines }}"

- set_fact: network_manager_unmanaged_devices="{{network_manager_unmanaged_devices}} + [ 'interface-name:lxdbr0' ]"