---

- name: Add x2go ppa
  apt_repository: repo=ppa:x2go/stable

- name: Installing remote app
  package: name={{item}}
  with_items:
    - freerdp-x11
    - remmina
    - remmina-plugin-rdp
    - remmina-plugin-vnc
    - x2goserver
    - x2goserver-extensions
    - x2goclient

- name: Patch x2goagent
  lineinfile:
    dest: /etc/x2go/x2goagent.options
    regexp: "^X2GO_NXAGENT_DEFAULT_OPTIONS="
    line: 'X2GO_NXAGENT_DEFAULT_OPTIONS="-extension BIG-REQUESTS"'


- stat: path=/usr/bin/teamviewer
  register: teamviewer_stat

- name: Downloading Teamviewer
  get_url: url=http://download.teamviewer.com/download/teamviewer_i386.deb dest=/tmp/teamviewer.deb
  when: not teamviewer_stat.stat.exists

- name: Installing Teamviewer
  apt: deb=/tmp/teamviewer.deb
  when: not teamviewer_stat.stat.exists

- name: Disable teamviewer startup
  service: name="teamviewerd" state=stopped enabled=no