---

- name: Adding Signal repository key
  apt_key:
    url: "https://updates.signal.org/desktop/apt/keys.asc"
    state: present
  when: gui

- name: Adding Signal repository
  apt_repository:
    repo: "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
    state: present
    filename: signal-xenial.list
  when: gui

- name: Installing communication apps (gui)
  apt:
    name: "{{item}}"
  when: gui
  with_items:
    - evolution
    - evolution-plugins
    - evolution-ews
    - pidgin
    - signal-desktop

- name: Installing skype
  shell:
    snap install skype
  creates: "/snap/bin/skype"
  when: gui

- name: Installing slack
  shell:
    snap install slack
  creates: "/snap/bin/slack"
  when: gui