---


- name: Installing communication apps (gui)
  apt:
    name: "{{item}}"
  when: gui
  with_items:
    - evolution
    - evolution-plugins
    - evolution-ews
    - pidgin

- name: Installing skype
  shell:
    snap install skype
  creates: "/snap/bin/skype"
  when: gui

- name: Installing slack
  shell:
    snap install slack
  creates: "/snap/bin/slack"
  when: gui