---

- name: Installing tools
  apt:
    name: "{{item}}"
  with_items:
    - bash-completion
    - zsh
    - ncdu
    - telnet
    - rsync
    - screen
    - lm-sensors
    - unrar
    - unzip
    - p7zip-full
    - iftop
    - htop
    - iotop
    - tcpdump

- name: Installing tools (Gui)
  apt:
    name: "{{item}}"
  when: gui
  with_items:
    - bleachbit
    - gparted
