---

- name: Installing security apps
  apt:
    name: "{{item}}"
  with_items:
    - gnupg2
    - gnupg-agent
    - pcscd
    - scdaemon
    - yubikey-personalization
    - yubikey-luks

- name: Installing security graphical apps
  apt:
    name: "{{item}}"
  when: gui
  with_items:
    - keepassxc
    - pinentry-gtk2
    - yubikey-personalization-gui
