---

- name: Installing other network manager protocol
  apt:
    name: "{{item}}"
  with_items:
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - network-manager-vpnc
    - network-manager-vpnc-gnome

- name: Installing nautilus addons
  apt:
    name: "{{item}}"
  with_items: 
    - nautilus-share

- name: Installing nautilus addons
  apt:
    name: "{{item}}"
  with_items:
    - chrome-gnome-shell
    - gnome-tweaks
