---

- name: Installing git
  apt:
    name: "{{item}}"
  with_items:
    - git
    - git-flow

- name: Installing git tools (Gui)
  apt:
    name: "{{item}}"
  when: gui
  with_items:
    - gitk
    - gitg
    - meld
    - diffuse

- name: Installing DB tools
  apt:
    name: "{{item}}"
  when: gui
  with_items:
    - mysql-workbench
    - pgadmin3

- name: Installing ubuntu-make
  apt:
    name: ubuntu-make
  
- name: Changing Inotify Watches Limit
  sysctl: name="fs.inotify.max_user_watches" value=524288 sysctl_set=yes state=present reload=yes sysctl_file=/etc/sysctl.conf
